"""
twpa.core.frequency_plan
========================

Frequency bookkeeping for harmonic-balance and conversion-matrix simulation.

The simulator uses explicit frequency plans for three related tasks:

1. Pump-only HB
   Solve the large-signal nonlinear periodic state generated by the pump and
   its harmonics.

2. Small-signal conversion around a pumped solution
   Linearize the circuit equations around the pump-only HB state and solve for
   signal/idler/sideband response.

3. Finite-signal HB
   Later, solve the full nonlinear pump + signal + idler problem for gain
   compression and pump depletion.

Why this exists
---------------
A TWPA is not simply "pump, signal, idler". Realistic harmonic-balance and
X-parameter style simulations use a multi-frequency basis. For degenerate
four-wave mixing, the primary idler satisfies

    f_i = 2 f_p - f_s

and higher sidebands can be written in a signed, double-sided convention as

    omega_k = 2 k omega_p + omega_s

where k = 0 gives the signal and k = -1 gives the negative-frequency idler
component omega_s - 2 omega_p = -omega_i.

The double-sided representation is important for:
- conjugate-symmetry checks,
- nonlinear mixing products,
- X-parameter/sensitivity-matrix indexing,
- later quantum-adapted conversion matrices.

Conventions
-----------
- Frequencies in this file are ordinary frequencies in Hz unless a property or
  function explicitly says angular frequency.
- Angular frequencies are omega = 2 pi f in rad/s.
- Frequency arrays may contain negative entries in double-sided plans.
- Public APIs preserve labels, so downstream code can identify signal, idler,
  pump, harmonics, and auxiliary sidebands.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from enum import Enum
from typing import Any, Iterable, Literal, Mapping

import jax
import jax.numpy as jnp

from .params import MixingRegime, PumpConfig, SignalConfig
from .units import GHz, angular_frequency, frequency_from_angular


ArrayLike = Any


# ---------------------------------------------------------------------------
# Enums and scalar helpers
# ---------------------------------------------------------------------------

class ToneRole(str, Enum):
    """Semantic role of a frequency tone."""

    DC = "dc"
    PUMP = "pump"
    PUMP_HARMONIC = "pump_harmonic"
    SIGNAL = "signal"
    IDLER = "idler"
    SIDEBAND = "sideband"
    AUXILIARY = "auxiliary"


class FrequencyPlanKind(str, Enum):
    """Kind of frequency plan."""

    PUMP_ONLY = "pump_only"
    DP4WM_SIGNAL_IDLER = "dp4wm_signal_idler"
    NP4WM_SIGNAL_IDLER = "np4wm_signal_idler"
    FINITE_SIGNAL_HB = "finite_signal_hb"
    CUSTOM = "custom"


def _check_positive(name: str, value: float) -> None:
    if float(value) <= 0.0:
        raise ValueError(f"{name} must be positive, got {value!r}")


def _as_1d_float_array(name: str, value: ArrayLike) -> jax.Array:
    arr = jnp.asarray(value, dtype=jnp.float64)
    if arr.ndim != 1:
        raise ValueError(f"{name} must be a 1D array, got shape {arr.shape}")
    return arr


def _unique_labels(labels: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for label in labels:
        if label in seen:
            raise ValueError(f"Duplicate tone label {label!r}")
        seen.add(label)
        out.append(label)
    return out


def _jsonify(obj: Any) -> Any:
    if isinstance(obj, Enum):
        return obj.value
    if isinstance(obj, dict):
        return {str(k): _jsonify(v) for k, v in obj.items()}
    if isinstance(obj, (tuple, list)):
        return [_jsonify(v) for v in obj]
    if hasattr(obj, "shape") and hasattr(obj, "dtype"):
        return {
            "array_shape": tuple(int(s) for s in obj.shape),
            "array_dtype": str(obj.dtype),
        }
    return obj


def nearly_equal_frequency_mask(
    frequencies_hz: ArrayLike,
    target_hz: float,
    *,
    atol_hz: float = 1e-6,
    rtol: float = 1e-12,
) -> jax.Array:
    """
    Return boolean mask for frequencies approximately equal to target_hz.
    """
    f = jnp.asarray(frequencies_hz)
    return jnp.abs(f - target_hz) <= (atol_hz + rtol * jnp.abs(target_hz))


# ---------------------------------------------------------------------------
# Tone and frequency-plan objects
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Tone:
    """
    One named frequency tone.

    Parameters
    ----------
    label:
        Unique label, e.g. "pump_1", "signal", "idler_primary".
    frequency_hz:
        Signed frequency in Hz. May be negative in double-sided plans.
    role:
        Semantic tone role.
    index:
        Integer sideband/harmonic index. Meaning depends on the plan.
    metadata:
        Small static metadata dictionary.
    """

    label: str
    frequency_hz: float
    role: ToneRole
    index: int = 0
    metadata: Mapping[str, Any] | None = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "role", ToneRole(self.role))
        if self.frequency_hz == 0.0 and self.role != ToneRole.DC:
            raise ValueError("Only DC tones may have exactly zero frequency")
        object.__setattr__(self, "index", int(self.index))
        if self.metadata is None:
            object.__setattr__(self, "metadata", {})
        else:
            object.__setattr__(self, "metadata", dict(self.metadata))

    @property
    def angular_frequency_rad_s(self) -> float:
        return float(2.0 * jnp.pi * self.frequency_hz)

    @property
    def abs_frequency_hz(self) -> float:
        return abs(float(self.frequency_hz))

    @property
    def is_positive_frequency(self) -> bool:
        return self.frequency_hz > 0.0

    @property
    def is_negative_frequency(self) -> bool:
        return self.frequency_hz < 0.0

    def conjugate_label(self) -> str:
        """Suggested label for the conjugate/signed-opposite tone."""
        if self.label.startswith("neg_"):
            return self.label[4:]
        return "neg_" + self.label

    def conjugate(self) -> "Tone":
        """
        Return the signed-opposite tone.

        This is useful for double-sided bookkeeping. The role is preserved.
        """
        return Tone(
            label=self.conjugate_label(),
            frequency_hz=-self.frequency_hz,
            role=self.role,
            index=-self.index,
            metadata={**dict(self.metadata or {}), "conjugate_of": self.label},
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "label": self.label,
            "frequency_hz": self.frequency_hz,
            "frequency_GHz": self.frequency_hz / GHz,
            "angular_frequency_rad_s": self.angular_frequency_rad_s,
            "role": self.role.value,
            "index": self.index,
            "metadata": _jsonify(dict(self.metadata or {})),
        }


@jax.tree_util.register_pytree_node_class
@dataclass(frozen=True)
class FrequencyPlan:
    """
    Vectorized frequency plan used by HB and conversion calculations.

    Parameters
    ----------
    frequencies_hz:
        Signed ordinary frequencies in Hz, shape (K,).
    labels:
        Unique labels, length K.
    roles:
        Tone roles, length K.
    indices:
        Integer harmonic/sideband indices, length K.
    kind:
        Plan kind.
    reference_pump_hz:
        Main pump frequency, if applicable.
    reference_signal_hz:
        Signal frequency, if applicable.
    metadata:
        Small static dictionary.

    JAX PyTree behavior
    -------------------
    frequencies_hz and indices are dynamic leaves. Labels/roles/kind/metadata
    are static auxiliary data.
    """

    frequencies_hz: jax.Array
    labels: tuple[str, ...]
    roles: tuple[ToneRole, ...]
    indices: jax.Array
    kind: FrequencyPlanKind = FrequencyPlanKind.CUSTOM
    reference_pump_hz: float | None = None
    reference_signal_hz: float | None = None
    metadata: Mapping[str, Any] | None = None

    def __post_init__(self) -> None:
        f = _as_1d_float_array("frequencies_hz", self.frequencies_hz)
        idx = _as_1d_float_array("indices", self.indices).astype(jnp.int32)

        labels = tuple(_unique_labels(tuple(self.labels)))
        roles = tuple(ToneRole(r) for r in self.roles)

        k = int(f.shape[0])
        if len(labels) != k:
            raise ValueError(f"labels length {len(labels)} does not match K={k}")
        if len(roles) != k:
            raise ValueError(f"roles length {len(roles)} does not match K={k}")
        if idx.shape[0] != k:
            raise ValueError(f"indices length {idx.shape[0]} does not match K={k}")

        if bool(jnp.any(jnp.isnan(f))):
            raise ValueError("frequencies_hz contains NaN")
        if bool(jnp.any(jnp.isinf(f))):
            raise ValueError("frequencies_hz contains inf")
        if bool(jnp.any(f == 0.0)):
            zero_roles = [roles[i] for i in range(k) if float(f[i]) == 0.0]
            if any(role != ToneRole.DC for role in zero_roles):
                raise ValueError("Only DC tones may have zero frequency")

        object.__setattr__(self, "frequencies_hz", f)
        object.__setattr__(self, "indices", idx)
        object.__setattr__(self, "labels", labels)
        object.__setattr__(self, "roles", roles)
        object.__setattr__(self, "kind", FrequencyPlanKind(self.kind))
        if self.reference_pump_hz is not None:
            _check_positive("reference_pump_hz", self.reference_pump_hz)
        if self.reference_signal_hz is not None:
            _check_positive("reference_signal_hz", self.reference_signal_hz)
        if self.metadata is None:
            object.__setattr__(self, "metadata", {})
        else:
            object.__setattr__(self, "metadata", dict(self.metadata))

    # ------------------------------------------------------------------
    # JAX PyTree implementation
    # ------------------------------------------------------------------

    def tree_flatten(self) -> tuple[tuple[jax.Array, jax.Array], dict[str, Any]]:
        children = (self.frequencies_hz, self.indices)
        aux = {
            "labels": self.labels,
            "roles": self.roles,
            "kind": self.kind,
            "reference_pump_hz": self.reference_pump_hz,
            "reference_signal_hz": self.reference_signal_hz,
            "metadata": dict(self.metadata or {}),
        }
        return children, aux

    @classmethod
    def tree_unflatten(
        cls,
        aux: dict[str, Any],
        children: tuple[jax.Array, jax.Array],
    ) -> "FrequencyPlan":
        return cls(
            frequencies_hz=children[0],
            labels=aux["labels"],
            roles=aux["roles"],
            indices=children[1],
            kind=aux["kind"],
            reference_pump_hz=aux["reference_pump_hz"],
            reference_signal_hz=aux["reference_signal_hz"],
            metadata=aux["metadata"],
        )

    # ------------------------------------------------------------------
    # Basic properties
    # ------------------------------------------------------------------

    @property
    def n_tones(self) -> int:
        return int(self.frequencies_hz.shape[0])

    @property
    def angular_frequencies_rad_s(self) -> jax.Array:
        return angular_frequency(self.frequencies_hz)

    @property
    def abs_frequencies_hz(self) -> jax.Array:
        return jnp.abs(self.frequencies_hz)

    @property
    def positive_frequency_mask(self) -> jax.Array:
        return self.frequencies_hz > 0.0

    @property
    def negative_frequency_mask(self) -> jax.Array:
        return self.frequencies_hz < 0.0

    @property
    def dc_mask(self) -> jax.Array:
        return self.frequencies_hz == 0.0

    @property
    def sorted_by_frequency(self) -> "FrequencyPlan":
        order = jnp.argsort(self.frequencies_hz)
        labels = tuple(self.labels[int(i)] for i in order)
        roles = tuple(self.roles[int(i)] for i in order)
        return FrequencyPlan(
            frequencies_hz=self.frequencies_hz[order],
            labels=labels,
            roles=roles,
            indices=self.indices[order],
            kind=self.kind,
            reference_pump_hz=self.reference_pump_hz,
            reference_signal_hz=self.reference_signal_hz,
            metadata={**dict(self.metadata or {}), "sorted": "frequency"},
        )

    @property
    def sorted_by_abs_frequency(self) -> "FrequencyPlan":
        order = jnp.argsort(jnp.abs(self.frequencies_hz))
        labels = tuple(self.labels[int(i)] for i in order)
        roles = tuple(self.roles[int(i)] for i in order)
        return FrequencyPlan(
            frequencies_hz=self.frequencies_hz[order],
            labels=labels,
            roles=roles,
            indices=self.indices[order],
            kind=self.kind,
            reference_pump_hz=self.reference_pump_hz,
            reference_signal_hz=self.reference_signal_hz,
            metadata={**dict(self.metadata or {}), "sorted": "abs_frequency"},
        )

    # ------------------------------------------------------------------
    # Lookup helpers
    # ------------------------------------------------------------------

    def role_mask(self, role: ToneRole | str) -> jax.Array:
        role = ToneRole(role)
        return jnp.asarray([r == role for r in self.roles], dtype=bool)

    def labels_for_role(self, role: ToneRole | str) -> list[str]:
        role = ToneRole(role)
        return [label for label, r in zip(self.labels, self.roles) if r == role]

    def positions_for_role(self, role: ToneRole | str) -> list[int]:
        role = ToneRole(role)
        return [i for i, r in enumerate(self.roles) if r == role]

    def position_of_label(self, label: str) -> int:
        try:
            return self.labels.index(label)
        except ValueError as exc:
            raise KeyError(f"Unknown tone label {label!r}") from exc

    def frequency_of_label(self, label: str) -> float:
        return float(self.frequencies_hz[self.position_of_label(label)])

    def angular_frequency_of_label(self, label: str) -> float:
        return float(self.angular_frequencies_rad_s[self.position_of_label(label)])

    def has_label(self, label: str) -> bool:
        return label in self.labels

    def tone(self, label: str) -> Tone:
        pos = self.position_of_label(label)
        return Tone(
            label=self.labels[pos],
            frequency_hz=float(self.frequencies_hz[pos]),
            role=self.roles[pos],
            index=int(self.indices[pos]),
            metadata={"plan_kind": self.kind.value},
        )

    def tones(self) -> list[Tone]:
        return [
            Tone(
                label=self.labels[i],
                frequency_hz=float(self.frequencies_hz[i]),
                role=self.roles[i],
                index=int(self.indices[i]),
                metadata={"plan_kind": self.kind.value},
            )
            for i in range(self.n_tones)
        ]

    def find_frequency(
        self,
        target_hz: float,
        *,
        atol_hz: float = 1e-6,
        rtol: float = 1e-12,
    ) -> list[int]:
        mask = nearly_equal_frequency_mask(
            self.frequencies_hz,
            target_hz,
            atol_hz=atol_hz,
            rtol=rtol,
        )
        return [i for i, value in enumerate(mask.tolist()) if bool(value)]

    def conjugate_position_map(
        self,
        *,
        atol_hz: float = 1e-6,
        rtol: float = 1e-12,
        require_all: bool = False,
    ) -> dict[int, int | None]:
        """
        Map each tone position to the position of its negative-frequency partner.

        If require_all is true, raise if a conjugate is missing.
        """
        mapping: dict[int, int | None] = {}
        for i, f in enumerate(self.frequencies_hz.tolist()):
            matches = self.find_frequency(-float(f), atol_hz=atol_hz, rtol=rtol)
            if len(matches) == 0:
                if require_all:
                    raise ValueError(
                        f"No conjugate frequency found for position {i}, f={f}"
                    )
                mapping[i] = None
            elif len(matches) == 1:
                mapping[i] = matches[0]
            else:
                raise ValueError(
                    f"Multiple conjugate matches found for position {i}, f={f}: {matches}"
                )
        return mapping

    # ------------------------------------------------------------------
    # Conversion / summaries
    # ------------------------------------------------------------------

    def with_updates(self, **kwargs: Any) -> "FrequencyPlan":
        return replace(self, **kwargs)

    def with_metadata(self, **metadata_updates: Any) -> "FrequencyPlan":
        current = dict(self.metadata or {})
        current.update(metadata_updates)
        return replace(self, metadata=current)

    def to_dict(self) -> dict[str, Any]:
        return {
            "kind": self.kind.value,
            "n_tones": self.n_tones,
            "reference_pump_hz": self.reference_pump_hz,
            "reference_signal_hz": self.reference_signal_hz,
            "tones": [tone.to_dict() for tone in self.tones()],
            "metadata": _jsonify(dict(self.metadata or {})),
        }

    def summary_table(self) -> str:
        lines = [
            f"FrequencyPlan(kind={self.kind.value}, K={self.n_tones})",
            "idx | label | role | f_GHz | omega_rad_s",
            "--- | --- | --- | ---: | ---:",
        ]
        for i in range(self.n_tones):
            f = float(self.frequencies_hz[i])
            omega = float(self.angular_frequencies_rad_s[i])
            lines.append(
                f"{i} | {self.labels[i]} | {self.roles[i].value} | "
                f"{f / GHz:.9g} | {omega:.9e}"
            )
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Plan constructors
# ---------------------------------------------------------------------------

def make_pump_only_plan(
    pump_frequency_hz: float,
    *,
    n_harmonics: int = 3,
    include_negative: bool = False,
    include_dc: bool = False,
    sort: Literal["none", "frequency", "abs_frequency"] = "abs_frequency",
) -> FrequencyPlan:
    """
    Create a pump-only frequency plan.

    Positive-only example for n_harmonics=3:
        +fp, +2fp, +3fp

    Double-sided example:
        -3fp, -2fp, -fp, +fp, +2fp, +3fp
        with optional DC tone.

    This plan is used for large-signal pump-only HB.
    """
    _check_positive("pump_frequency_hz", pump_frequency_hz)
    if int(n_harmonics) <= 0:
        raise ValueError("n_harmonics must be positive")
    n_harmonics = int(n_harmonics)

    tones: list[Tone] = []

    if include_dc:
        tones.append(Tone(label="dc", frequency_hz=0.0, role=ToneRole.DC, index=0))

    if include_negative:
        for n in range(n_harmonics, 0, -1):
            role = ToneRole.PUMP if n == 1 else ToneRole.PUMP_HARMONIC
            tones.append(
                Tone(
                    label=f"neg_pump_{n}",
                    frequency_hz=-n * pump_frequency_hz,
                    role=role,
                    index=-n,
                    metadata={"harmonic": n},
                )
            )

    for n in range(1, n_harmonics + 1):
        role = ToneRole.PUMP if n == 1 else ToneRole.PUMP_HARMONIC
        label = "pump" if n == 1 else f"pump_{n}"
        tones.append(
            Tone(
                label=label,
                frequency_hz=n * pump_frequency_hz,
                role=role,
                index=n,
                metadata={"harmonic": n},
            )
        )

    plan = _plan_from_tones(
        tones,
        kind=FrequencyPlanKind.PUMP_ONLY,
        reference_pump_hz=pump_frequency_hz,
        reference_signal_hz=None,
        metadata={
            "n_harmonics": n_harmonics,
            "include_negative": include_negative,
            "include_dc": include_dc,
        },
    )

    return _sort_plan(plan, sort)


def make_pump_only_plan_from_config(
    pump: PumpConfig,
    *,
    include_negative: bool = False,
    include_dc: bool = False,
    sort: Literal["none", "frequency", "abs_frequency"] = "abs_frequency",
) -> FrequencyPlan:
    """Create a pump-only plan from PumpConfig."""
    return make_pump_only_plan(
        pump.frequency_hz,
        n_harmonics=pump.harmonics,
        include_negative=include_negative,
        include_dc=include_dc,
        sort=sort,
    )


def make_dp4wm_signal_idler_plan(
    pump_frequency_hz: float,
    signal_frequency_hz: float,
    *,
    sideband_order: int = 3,
    include_pump: bool = True,
    include_pump_harmonics: int = 3,
    include_negative_conjugates: bool = True,
    sort: Literal["none", "frequency", "abs_frequency"] = "frequency",
) -> FrequencyPlan:
    """
    Create a degenerate-pump 4WM small-signal/idler plan.

    Signal/idler sidebands are generated by:

        f_k = f_s + 2 k f_p

    where k is an integer. k=0 is the signal. k=-1 is the negative-frequency
    representation of the primary idler:

        f_{-1} = f_s - 2 f_p = -(2 f_p - f_s) = -f_i

    Parameters
    ----------
    pump_frequency_hz:
        Pump frequency fp.
    signal_frequency_hz:
        Signal frequency fs.
    sideband_order:
        Include k from -sideband_order to +sideband_order.
    include_pump:
        Add +fp as a tone.
    include_pump_harmonics:
        Add pump harmonics +n fp for n=1..include_pump_harmonics if
        include_pump is true. If include_pump is false, this is ignored.
    include_negative_conjugates:
        Ensure signed-opposite partners are included for signal/idler sideband
        tones and pump tones.
    """
    _check_positive("pump_frequency_hz", pump_frequency_hz)
    _check_positive("signal_frequency_hz", signal_frequency_hz)
    if int(sideband_order) < 1:
        raise ValueError("sideband_order must be >= 1")
    sideband_order = int(sideband_order)
    include_pump_harmonics = int(include_pump_harmonics)
    if include_pump_harmonics < 0:
        raise ValueError("include_pump_harmonics must be non-negative")

    tones: list[Tone] = []

    # Signal/idler double-sided sideband set.
    for k in range(-sideband_order, sideband_order + 1):
        f = signal_frequency_hz + 2.0 * k * pump_frequency_hz

        if k == 0:
            role = ToneRole.SIGNAL
            label = "signal"
        elif k == -1:
            role = ToneRole.IDLER
            label = "neg_idler_primary"
        elif k == 1:
            role = ToneRole.SIDEBAND
            label = "upper_sideband_k1"
        elif k < -1:
            role = ToneRole.SIDEBAND
            label = f"lower_sideband_k{k}"
        else:
            role = ToneRole.SIDEBAND
            label = f"upper_sideband_k{k}"

        if f == 0.0:
            raise ValueError(
                "Generated zero-frequency sideband. Choose non-degenerate "
                "pump/signal frequencies or exclude that sideband."
            )

        tones.append(
            Tone(
                label=label,
                frequency_hz=f,
                role=role,
                index=k,
                metadata={
                    "formula": "f_k = f_s + 2 k f_p",
                    "k": k,
                    "pump_frequency_hz": pump_frequency_hz,
                    "signal_frequency_hz": signal_frequency_hz,
                },
            )
        )

    # Optional explicit conjugates of the generated sideband set.
    if include_negative_conjugates:
        tones = _add_missing_conjugate_tones(tones)

    # Optional pump and harmonics.
    if include_pump:
        pump_tones: list[Tone] = []
        for n in range(1, include_pump_harmonics + 1):
            role = ToneRole.PUMP if n == 1 else ToneRole.PUMP_HARMONIC
            label = "pump" if n == 1 else f"pump_{n}"
            pump_tones.append(
                Tone(
                    label=label,
                    frequency_hz=n * pump_frequency_hz,
                    role=role,
                    index=n,
                    metadata={"harmonic": n},
                )
            )
        if include_negative_conjugates:
            pump_tones = _add_missing_conjugate_tones(pump_tones)
        tones.extend(pump_tones)

    # Remove exact duplicate frequencies/labels in a conservative way.
    tones = _deduplicate_tones_by_label_and_frequency(tones)

    plan = _plan_from_tones(
        tones,
        kind=FrequencyPlanKind.DP4WM_SIGNAL_IDLER,
        reference_pump_hz=pump_frequency_hz,
        reference_signal_hz=signal_frequency_hz,
        metadata={
            "sideband_order": sideband_order,
            "include_pump": include_pump,
            "include_pump_harmonics": include_pump_harmonics,
            "include_negative_conjugates": include_negative_conjugates,
            "primary_idler_frequency_hz": 2.0 * pump_frequency_hz - signal_frequency_hz,
        },
    )

    return _sort_plan(plan, sort)


def make_dp4wm_signal_idler_plan_from_config(
    pump: PumpConfig,
    signal_frequency_hz: float,
    *,
    signal: SignalConfig | None = None,
    sideband_order: int | None = None,
    include_pump: bool = True,
    include_pump_harmonics: int | None = None,
    include_negative_conjugates: bool = True,
    sort: Literal["none", "frequency", "abs_frequency"] = "frequency",
) -> FrequencyPlan:
    """Create a DP4WM plan using PumpConfig and optional SignalConfig."""
    if sideband_order is None:
        sideband_order = signal.sideband_order if signal is not None else 3
    if include_pump_harmonics is None:
        include_pump_harmonics = pump.harmonics
    return make_dp4wm_signal_idler_plan(
        pump.frequency_hz,
        signal_frequency_hz,
        sideband_order=sideband_order,
        include_pump=include_pump,
        include_pump_harmonics=include_pump_harmonics,
        include_negative_conjugates=include_negative_conjugates,
        sort=sort,
    )


def make_finite_signal_hb_plan_dp4wm(
    pump_frequency_hz: float,
    signal_frequency_hz: float,
    *,
    pump_harmonics: int = 3,
    sideband_order: int = 2,
    include_negative: bool = True,
    include_dc: bool = False,
    sort: Literal["none", "frequency", "abs_frequency"] = "frequency",
) -> FrequencyPlan:
    """
    Frequency plan for finite-signal HB in DP4WM.

    This combines pump harmonics and signal/idler sidebands into one plan.
    It is intended for compression simulations after the pump-only and
    linearized conversion solvers are validated.
    """
    pump_plan = make_pump_only_plan(
        pump_frequency_hz,
        n_harmonics=pump_harmonics,
        include_negative=include_negative,
        include_dc=include_dc,
        sort="none",
    )
    conversion_plan = make_dp4wm_signal_idler_plan(
        pump_frequency_hz,
        signal_frequency_hz,
        sideband_order=sideband_order,
        include_pump=False,
        include_negative_conjugates=include_negative,
        sort="none",
    )
    tones = pump_plan.tones() + conversion_plan.tones()
    tones = _deduplicate_tones_by_label_and_frequency(tones)

    plan = _plan_from_tones(
        tones,
        kind=FrequencyPlanKind.FINITE_SIGNAL_HB,
        reference_pump_hz=pump_frequency_hz,
        reference_signal_hz=signal_frequency_hz,
        metadata={
            "mixing_regime": MixingRegime.DP4WM.value,
            "pump_harmonics": pump_harmonics,
            "sideband_order": sideband_order,
            "include_negative": include_negative,
            "include_dc": include_dc,
        },
    )
    return _sort_plan(plan, sort)


def make_multi_signal_idler_plan(
    pump_frequency_hz: float,
    signal_frequencies_hz: ArrayLike,
    idler_frequencies_hz: ArrayLike,
    *,
    pump_label: str = "pump",
    signal_labels: Iterable[str] | None = None,
    idler_labels: Iterable[str] | None = None,
    n_pump_harmonics: int = 3,
    include_negative: bool = True,
    include_dc: bool = False,
    sort: Literal["none", "frequency", "abs_frequency"] = "frequency",
) -> FrequencyPlan:
    """Build one target plan for a labelled signal/idler gain sweep."""
    _check_positive("pump_frequency_hz", pump_frequency_hz)
    fs = _as_1d_float_array("signal_frequencies_hz", signal_frequencies_hz)
    fi = _as_1d_float_array("idler_frequencies_hz", idler_frequencies_hz)
    if fs.shape != fi.shape:
        raise ValueError("signal_frequencies_hz and idler_frequencies_hz must have the same shape")
    if bool(jnp.any(fs <= 0.0)) or bool(jnp.any(fi <= 0.0)):
        raise ValueError("signal and idler frequencies must be positive")
    if int(n_pump_harmonics) <= 0:
        raise ValueError("n_pump_harmonics must be positive")

    n_points = int(fs.shape[0])
    sig_labels = tuple(signal_labels or (f"signal_{i}" for i in range(n_points)))
    idl_labels = tuple(idler_labels or (f"idler_{i}" for i in range(n_points)))
    if len(sig_labels) != n_points or len(idl_labels) != n_points:
        raise ValueError("signal_labels and idler_labels must match the frequency array length")

    tones: list[Tone] = []
    if include_dc:
        tones.append(Tone(label="dc", frequency_hz=0.0, role=ToneRole.DC))

    pump_tones = [
        Tone(
            label=pump_label if harmonic == 1 else f"{pump_label}_{harmonic}",
            frequency_hz=harmonic * pump_frequency_hz,
            role=ToneRole.PUMP if harmonic == 1 else ToneRole.PUMP_HARMONIC,
            index=harmonic,
            metadata={"harmonic": harmonic},
        )
        for harmonic in range(1, int(n_pump_harmonics) + 1)
    ]
    tones.extend(_add_missing_conjugate_tones(pump_tones) if include_negative else pump_tones)

    conversion_tones = [
        Tone(label=label, frequency_hz=float(freq), role=ToneRole.SIGNAL, index=index)
        for index, (label, freq) in enumerate(zip(sig_labels, fs))
    ]
    conversion_tones.extend(
        Tone(label=label, frequency_hz=float(freq), role=ToneRole.IDLER, index=index)
        for index, (label, freq) in enumerate(zip(idl_labels, fi))
    )
    tones.extend(
        _add_missing_conjugate_tones(conversion_tones)
        if include_negative
        else conversion_tones
    )

    plan = _plan_from_tones(
        _deduplicate_tones_by_label_and_frequency(tones),
        kind=FrequencyPlanKind.DP4WM_SIGNAL_IDLER,
        reference_pump_hz=pump_frequency_hz,
        reference_signal_hz=float(fs[0]) if n_points else None,
        metadata={
            "n_signal_idler_pairs": n_points,
            "n_pump_harmonics": int(n_pump_harmonics),
            "include_negative": include_negative,
            "include_dc": include_dc,
        },
    )
    return _sort_plan(plan, sort)


def make_custom_plan(
    tones: Iterable[Tone],
    *,
    kind: FrequencyPlanKind | str = FrequencyPlanKind.CUSTOM,
    reference_pump_hz: float | None = None,
    reference_signal_hz: float | None = None,
    metadata: Mapping[str, Any] | None = None,
    sort: Literal["none", "frequency", "abs_frequency"] = "none",
) -> FrequencyPlan:
    """Create a custom frequency plan from explicit Tone objects."""
    plan = _plan_from_tones(
        list(tones),
        kind=kind,
        reference_pump_hz=reference_pump_hz,
        reference_signal_hz=reference_signal_hz,
        metadata=metadata,
    )
    return _sort_plan(plan, sort)


# ---------------------------------------------------------------------------
# Plan internals
# ---------------------------------------------------------------------------

def _plan_from_tones(
    tones: list[Tone],
    *,
    kind: FrequencyPlanKind | str,
    reference_pump_hz: float | None,
    reference_signal_hz: float | None,
    metadata: Mapping[str, Any] | None = None,
) -> FrequencyPlan:
    if len(tones) == 0:
        raise ValueError("Cannot build a FrequencyPlan with zero tones")

    labels = tuple(t.label for t in tones)
    _unique_labels(labels)

    frequencies = jnp.asarray([float(t.frequency_hz) for t in tones], dtype=jnp.float64)
    roles = tuple(t.role for t in tones)
    indices = jnp.asarray([int(t.index) for t in tones], dtype=jnp.int32)

    return FrequencyPlan(
        frequencies_hz=frequencies,
        labels=labels,
        roles=roles,
        indices=indices,
        kind=FrequencyPlanKind(kind),
        reference_pump_hz=reference_pump_hz,
        reference_signal_hz=reference_signal_hz,
        metadata=dict(metadata or {}),
    )


def _sort_plan(
    plan: FrequencyPlan,
    sort: Literal["none", "frequency", "abs_frequency"],
) -> FrequencyPlan:
    if sort == "none":
        return plan
    if sort == "frequency":
        return plan.sorted_by_frequency
    if sort == "abs_frequency":
        return plan.sorted_by_abs_frequency
    raise ValueError(f"Unsupported sort mode {sort!r}")


def _add_missing_conjugate_tones(
    tones: list[Tone],
    *,
    atol_hz: float = 1e-6,
    rtol: float = 1e-12,
) -> list[Tone]:
    """
    Add signed-opposite tones when missing.

    Labels are generated from Tone.conjugate_label(), with suffixes added if
    required to avoid collisions.
    """
    out = list(tones)
    freqs = [float(t.frequency_hz) for t in out]
    labels = {t.label for t in out}

    for tone in list(tones):
        target = -float(tone.frequency_hz)
        exists = any(abs(f - target) <= (atol_hz + rtol * abs(target)) for f in freqs)
        if exists:
            continue

        conj = tone.conjugate()
        label = conj.label
        if label in labels:
            base = label
            counter = 1
            while label in labels:
                label = f"{base}_{counter}"
                counter += 1
            conj = replace(conj, label=label)

        out.append(conj)
        freqs.append(float(conj.frequency_hz))
        labels.add(conj.label)

    return out


def _deduplicate_tones_by_label_and_frequency(
    tones: list[Tone],
    *,
    atol_hz: float = 1e-6,
    rtol: float = 1e-12,
) -> list[Tone]:
    """
    Conservative deduplication.

    If labels duplicate, rename later labels. If frequencies duplicate exactly
    within tolerance, keep both only if roles differ in a way that matters.
    For the first implementation, duplicate frequencies with different labels
    are allowed because pump harmonics can coincide with generated sidebands in
    some artificial test cases; downstream code can decide how to handle them.
    """
    out: list[Tone] = []
    used_labels: set[str] = set()

    for tone in tones:
        label = tone.label
        if label in used_labels:
            base = label
            counter = 1
            while label in used_labels:
                label = f"{base}_{counter}"
                counter += 1
            tone = replace(tone, label=label)
        out.append(tone)
        used_labels.add(tone.label)

    return out


# ---------------------------------------------------------------------------
# DP4WM/idler convenience functions
# ---------------------------------------------------------------------------

def dp4wm_primary_idler_frequency_hz(
    pump_frequency_hz: float,
    signal_frequency_hz: float,
) -> float:
    """
    Primary idler frequency for degenerate-pump 4WM.

        f_i = 2 f_p - f_s
    """
    _check_positive("pump_frequency_hz", pump_frequency_hz)
    _check_positive("signal_frequency_hz", signal_frequency_hz)
    return 2.0 * pump_frequency_hz - signal_frequency_hz


def dp4wm_primary_idler_angular_frequency_rad_s(
    pump_omega_rad_s: float,
    signal_omega_rad_s: float,
) -> float:
    """
    Primary idler angular frequency for DP4WM.

        omega_i = 2 omega_p - omega_s
    """
    _check_positive("pump_omega_rad_s", pump_omega_rad_s)
    _check_positive("signal_omega_rad_s", signal_omega_rad_s)
    return 2.0 * pump_omega_rad_s - signal_omega_rad_s


def dp4wm_sideband_frequencies_hz(
    pump_frequency_hz: float,
    signal_frequency_hz: float,
    *,
    sideband_order: int,
) -> jax.Array:
    """
    Return f_k = f_s + 2 k f_p for k=-order..order.
    """
    _check_positive("pump_frequency_hz", pump_frequency_hz)
    _check_positive("signal_frequency_hz", signal_frequency_hz)
    if int(sideband_order) < 1:
        raise ValueError("sideband_order must be >= 1")
    k = jnp.arange(-int(sideband_order), int(sideband_order) + 1)
    return signal_frequency_hz + 2.0 * k * pump_frequency_hz


def dp4wm_sideband_indices(sideband_order: int) -> jax.Array:
    """Return integer k indices for f_k = f_s + 2 k f_p."""
    if int(sideband_order) < 1:
        raise ValueError("sideband_order must be >= 1")
    return jnp.arange(-int(sideband_order), int(sideband_order) + 1, dtype=jnp.int32)


def dp4wm_lattice_indices_for_plan(
    plan: FrequencyPlan,
    *,
    atol_hz: float = 1e-3,
    rtol: float = 1e-12,
) -> jax.Array:
    """
    Return the two-dimensional DP4WM lattice vector for every plan tone.

    The lattice fundamentals are ``(f_p, f_s)``. Pump harmonics use ``(h, 0)``
    and signal/idler sidebands ``f_s + 2 k f_p`` use ``(2 k, 1)``. Signed
    conjugates negate both coordinates.
    """
    if plan.reference_pump_hz is None or plan.reference_signal_hz is None:
        raise ValueError("DP4WM lattice projection requires reference pump and signal frequencies")
    fp = float(plan.reference_pump_hz)
    fs = float(plan.reference_signal_hz)

    def close(actual: float, expected: float) -> bool:
        return abs(actual - expected) <= atol_hz + rtol * max(abs(actual), abs(expected))

    rows: list[tuple[int, int]] = []
    for label, frequency in zip(plan.labels, plan.frequencies_hz.tolist()):
        f = float(frequency)
        if close(f, 0.0):
            rows.append((0, 0))
            continue

        harmonic = int(round(f / fp))
        if close(f, harmonic * fp):
            rows.append((harmonic, 0))
            continue

        sideband = int(round((f - fs) / (2.0 * fp)))
        if close(f, fs + 2.0 * sideband * fp):
            rows.append((2 * sideband, 1))
            continue

        negative_sideband = int(round((-f - fs) / (2.0 * fp)))
        if close(f, -(fs + 2.0 * negative_sideband * fp)):
            rows.append((-2 * negative_sideband, -1))
            continue

        raise ValueError(
            f"Tone {label!r} at {f} Hz is not on the DP4WM (pump, signal) lattice"
        )

    return jnp.asarray(rows, dtype=jnp.int32)


def is_valid_dp4wm_signal_band(
    pump_frequency_hz: float,
    signal_frequency_hz: ArrayLike,
    *,
    require_positive_idler: bool = True,
) -> jax.Array:
    """
    Return mask indicating whether signal frequencies give valid idlers.

    If require_positive_idler is true, require 2 fp - fs > 0.
    """
    fs = jnp.asarray(signal_frequency_hz)
    fi = 2.0 * pump_frequency_hz - fs
    if require_positive_idler:
        return fi > 0.0
    return jnp.ones_like(fs, dtype=bool)


# ---------------------------------------------------------------------------
# Matrix indexing helpers for conversion matrices
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class PortFrequencyIndex:
    """
    Index mapping for multi-port, multi-frequency wave variables.

    For a two-port plan with K tones, the flattened wave vector can be ordered as

        flat_index = port_index * K + frequency_index

    where port_index is zero-based internally.

    This supports X-parameter-style conversion matrices:

        b[p, omega_j] = sum_{q,k} X[p,j;q,k] a[q,k]
    """

    n_ports: int
    frequency_plan: FrequencyPlan
    port_base: Literal[0, 1] = 1

    def __post_init__(self) -> None:
        if int(self.n_ports) <= 0:
            raise ValueError("n_ports must be positive")
        object.__setattr__(self, "n_ports", int(self.n_ports))
        if self.port_base not in {0, 1}:
            raise ValueError("port_base must be 0 or 1")

    @property
    def n_frequencies(self) -> int:
        return self.frequency_plan.n_tones

    @property
    def size(self) -> int:
        return self.n_ports * self.n_frequencies

    def _port_to_zero_based(self, port: int) -> int:
        p = int(port) - self.port_base
        if p < 0 or p >= self.n_ports:
            raise IndexError(
                f"port {port} out of range for n_ports={self.n_ports}, "
                f"port_base={self.port_base}"
            )
        return p

    def flat_index(self, port: int, frequency_position: int) -> int:
        p = self._port_to_zero_based(port)
        k = int(frequency_position)
        if k < 0 or k >= self.n_frequencies:
            raise IndexError(f"frequency_position {k} out of range")
        return p * self.n_frequencies + k

    def flat_index_label(self, port: int, label: str) -> int:
        return self.flat_index(port, self.frequency_plan.position_of_label(label))

    def unflatten_index(self, flat_index: int) -> tuple[int, int]:
        idx = int(flat_index)
        if idx < 0 or idx >= self.size:
            raise IndexError(f"flat_index {idx} out of range size={self.size}")
        p0 = idx // self.n_frequencies
        k = idx % self.n_frequencies
        return p0 + self.port_base, k

    def matrix_shape(self) -> tuple[int, int]:
        return (self.size, self.size)

    def labels(self) -> list[str]:
        out: list[str] = []
        for p0 in range(self.n_ports):
            p = p0 + self.port_base
            for label in self.frequency_plan.labels:
                out.append(f"p{p}:{label}")
        return out

    def to_dict(self) -> dict[str, Any]:
        return {
            "n_ports": self.n_ports,
            "n_frequencies": self.n_frequencies,
            "size": self.size,
            "port_base": self.port_base,
            "labels": self.labels(),
            "frequency_plan": self.frequency_plan.to_dict(),
        }


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------

def validate_frequency_plan(
    plan: FrequencyPlan,
    *,
    min_abs_frequency_hz: float = 1.0,
    max_abs_frequency_hz: float | None = None,
    require_unique_frequencies: bool = False,
    atol_hz: float = 1e-6,
    rtol: float = 1e-12,
) -> dict[str, Any]:
    """
    Validate a frequency plan and return a report.

    This function does not raise for validation failures except malformed input.
    """
    abs_f = jnp.abs(plan.frequencies_hz)
    nonzero_min = float(jnp.min(abs_f[abs_f > 0.0])) if bool(jnp.any(abs_f > 0.0)) else 0.0

    passed = True
    messages: list[str] = []

    if nonzero_min < min_abs_frequency_hz:
        passed = False
        messages.append(
            f"Minimum nonzero frequency {nonzero_min} Hz is below "
            f"min_abs_frequency_hz={min_abs_frequency_hz}."
        )

    max_abs = float(jnp.max(abs_f))
    if max_abs_frequency_hz is not None and max_abs > max_abs_frequency_hz:
        passed = False
        messages.append(
            f"Maximum frequency {max_abs} Hz exceeds max_abs_frequency_hz="
            f"{max_abs_frequency_hz}."
        )

    duplicate_pairs: list[tuple[int, int]] = []
    for i in range(plan.n_tones):
        for j in range(i + 1, plan.n_tones):
            fi = float(plan.frequencies_hz[i])
            fj = float(plan.frequencies_hz[j])
            if abs(fi - fj) <= (atol_hz + rtol * max(abs(fi), abs(fj))):
                duplicate_pairs.append((i, j))

    if require_unique_frequencies and duplicate_pairs:
        passed = False
        messages.append(f"Duplicate/equal frequencies found: {duplicate_pairs}")

    if not messages:
        messages.append("PASS: frequency plan validation checks passed.")

    return {
        "kind": plan.kind.value,
        "n_tones": plan.n_tones,
        "min_abs_frequency_hz": nonzero_min,
        "max_abs_frequency_hz": max_abs,
        "require_unique_frequencies": require_unique_frequencies,
        "duplicate_pairs": duplicate_pairs,
        "passed": bool(passed),
        "messages": messages,
    }


def validate_dp4wm_plan(
    plan: FrequencyPlan,
    *,
    atol_hz: float = 1e-6,
    rtol: float = 1e-12,
) -> dict[str, Any]:
    """
    Validate DP4WM-specific frequency relationships.

    Checks:
    - reference pump and signal exist,
    - primary idler relation f_i = 2 f_p - f_s is represented by
      a negative-frequency tone at f_s - 2 f_p or a positive idler tone.
    """
    passed = True
    messages: list[str] = []

    if plan.reference_pump_hz is None:
        passed = False
        messages.append("Missing reference_pump_hz.")
    if plan.reference_signal_hz is None:
        passed = False
        messages.append("Missing reference_signal_hz.")

    if plan.reference_pump_hz is not None and plan.reference_signal_hz is not None:
        fp = plan.reference_pump_hz
        fs = plan.reference_signal_hz
        fi = dp4wm_primary_idler_frequency_hz(fp, fs)
        neg_idler = fs - 2.0 * fp

        pos_matches = plan.find_frequency(fi, atol_hz=atol_hz, rtol=rtol)
        neg_matches = plan.find_frequency(neg_idler, atol_hz=atol_hz, rtol=rtol)

        if not pos_matches and not neg_matches:
            passed = False
            messages.append(
                "No primary idler representation found. Expected either "
                f"+fi={fi} Hz or -fi={neg_idler} Hz."
            )
        else:
            messages.append(
                f"Primary idler represented. positive_matches={pos_matches}, "
                f"negative_matches={neg_matches}."
            )

        signal_matches = plan.find_frequency(fs, atol_hz=atol_hz, rtol=rtol)
        if not signal_matches:
            passed = False
            messages.append(f"No signal tone found at fs={fs} Hz.")
        else:
            messages.append(f"Signal tone found at positions {signal_matches}.")

    if passed:
        messages.insert(0, "PASS: DP4WM frequency relationships validated.")
    else:
        messages.insert(0, "FAIL: DP4WM frequency relationship issue.")

    return {
        "kind": plan.kind.value,
        "passed": bool(passed),
        "messages": messages,
        "reference_pump_hz": plan.reference_pump_hz,
        "reference_signal_hz": plan.reference_signal_hz,
    }


__all__ = [
    "ToneRole",
    "FrequencyPlanKind",
    "Tone",
    "FrequencyPlan",
    "PortFrequencyIndex",
    "nearly_equal_frequency_mask",
    "make_pump_only_plan",
    "make_pump_only_plan_from_config",
    "make_dp4wm_signal_idler_plan",
    "make_dp4wm_signal_idler_plan_from_config",
    "make_finite_signal_hb_plan_dp4wm",
    "make_multi_signal_idler_plan",
    "make_custom_plan",
    "dp4wm_primary_idler_frequency_hz",
    "dp4wm_primary_idler_angular_frequency_rad_s",
    "dp4wm_sideband_frequencies_hz",
    "dp4wm_sideband_indices",
    "dp4wm_lattice_indices_for_plan",
    "is_valid_dp4wm_signal_band",
    "validate_frequency_plan",
    "validate_dp4wm_plan",
]
